/* eslint-disable */
// AUTO-GENERATED BY scripts/generate_shared_types.py
// Do not edit this file manually.

/** Album detail record returned by GET /api/albums/{id}. */
export interface AlbumDetailResponse {
  id: number;
  name: string;
  description?: string | null;
  album_type: string;
  is_public: boolean;
  generation_prompt?: string | null;
  generation_config?: string | null;
  created_by?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  image_count: number;
  is_set_template: boolean;
  csv_data?: string | null;
  base_prompt?: string | null;
  prompt_template?: string | null;
  style_suffix?: string | null;
  example_theme?: string | null;
  lora_config?: string | null;
  template_item_count: number;
  template_items_preview: Array<Record<string, unknown>>;
  lora_count: number;
  slug: string;
  images: Array<ImageResponse>;
  source_type?: string | null;
  source_id?: number | null;
}

/** Album record returned by /api/albums endpoints. */
export interface AlbumResponse {
  id: number;
  name: string;
  description?: string | null;
  album_type: string;
  is_public: boolean;
  generation_prompt?: string | null;
  generation_config?: string | null;
  created_by?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  image_count: number;
  is_set_template: boolean;
  csv_data?: string | null;
  base_prompt?: string | null;
  prompt_template?: string | null;
  style_suffix?: string | null;
  example_theme?: string | null;
  lora_config?: string | null;
  template_item_count: number;
  template_items_preview: Array<Record<string, unknown>>;
  preview_images?: Array<{ id: number; filename: string; thumbnail_path?: string | null }>;
  lora_count: number;
  slug: string;
  images?: Array<Record<string, unknown>>;
  source_type?: string | null;
  source_id?: number | null;
  total_images?: number;
  labeled_images?: number;
  ready_for_training?: boolean;
}

/** Response payload returned by /api/auth/me. */
export interface AuthStatus {
  authenticated: boolean;
  email?: string | null;
  name?: string | null;
  picture?: string | null;
  role?: string | null;
  is_admin?: boolean | null;
  error?: string | null;
  message?: string | null;
}

/** Response returned after queuing batch generation jobs. */
export interface BatchGenerationResponse {
  message: string;
  album_id: number;
  album_name: string;
  batch_id: string;
  job_ids: Array<number>;
  output_dir: string;
}

/** Summary record for generated image batches returned by /api/generation/batches. */
export interface BatchSummary {
  batch_id: string;
  album_id: number;
  name: string;
  album_type?: string | null;
  image_count: number;
  created?: string | null;
  updated?: string | null;
  preview_url?: string | null;
  path?: string | null;
}

/** Envelope returned by GET /api/generation/batches. */
export interface BatchesResponse {
  batches: Array<BatchSummary>;
}

/** Payload accepted by POST /api/bug-reports. */
export interface BugReportSubmissionRequest {
  description: string;
  expectedBehavior?: string | null;
  actualBehavior?: string | null;
  stepsToReproduce?: Array<string>;
  environment: { mode: string; appVersion?: string | null; gitSha?: string | null; buildTime?: string | null };
  clientMeta: { locationHref: string; userAgent?: string; platform?: string; language?: string; locale?: string; timezone?: string; viewport?: { width: number; height: number } };
  appState: Record<string, unknown>;
  recentLogs: Array<{ level: string; message: string; args: Array<unknown>; timestamp: string; serializedArgs: Array<unknown> }>;
  networkEvents: Array<{ id: string; method: string; url: string; started_at: string; completed_at?: string | null; duration_ms?: number | null; status?: number | null; ok?: boolean | null; trace_id?: string | null; requestHeaders: Array<{ name: string; value: string }>; responseHeaders: Array<{ name: string; value: string }>; requestBody?: string | null; responseBody?: string | null; error?: string }>;
  screenshot?: string | null;
  screenshotError?: string | null;
}

/** Response returned by POST /api/bug-reports. */
export interface BugReportSubmissionResponse {
  success: boolean;
  report_id: string;
  trace_id: string;
  stored_at?: string | null;
}

/** Generation metadata saved alongside generated images. */
export interface ImageMetadata {
  prompt?: string;
  negative_prompt?: string;
  seed?: number;
  steps?: number;
  guidance_scale?: number;
  width?: number;
  height?: number;
  model?: string;
  lora_path?: string;
  lora_weight?: number;
  loras?: Array<{ path: string; weight: number }>;
}

/** Complete image record returned by /api/images endpoints. */
export interface ImageResponse {
  id: number;
  filename: string;
  storage_name?: string | null;
  download_url: string;
  thumbnail_url: string;
  prompt?: string | null;
  negative_prompt?: string | null;
  seed?: number | null;
  steps?: number | null;
  guidance_scale?: number | null;
  width?: number | null;
  height?: number | null;
  lora_config?: string | null;
  is_nsfw: boolean;
  is_public: boolean;
  created_at?: string | null;
  updated_at?: string | null;
  file_path?: string | null;
  thumbnail_path?: string | null;
  labels?: Array<Label>;
  label_count?: number | null;
  manual_label_count?: number | null;
}

/** Job state returned by image generation endpoints. */
export interface Job {
  id: number;
  status: "queued" | "running" | "completed" | "failed" | "cancelled";
  prompt: string;
  queue_position?: number | null;
  submitted_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  cancelled_at?: string | null;
  created_at?: string;
  created?: string;
  output_path?: string | null;
  output_filename?: string;
  output_directory?: string;
  output_dir?: string;
  output?: string;
  lora_paths?: Array<string>;
  lora_weights?: Array<number>;
  width?: number;
  height?: number;
  steps?: number;
  seed?: number;
  guidance_scale?: number;
  negative_prompt?: string;
  error?: string | null;
  duration_seconds?: number;
  estimated_time_remaining?: number | null;
  album_id?: number;
  batch_id?: string;
  batch_item_name?: string;
  batch_item_data?: Record<string, unknown>;
}

/** Envelope returned by GET /api/jobs. */
export interface JobsResponse {
  current: Job | null;
  queue: Array<Job>;
  history: Array<Job>;
}

/** Label/tag associated with an image. */
export interface Label {
  id: number;
  image_id: number;
  label_text: string;
  confidence?: number | null;
  label_type: string;
  source_model?: string | null;
  source_prompt?: string | null;
  created_by?: string | null;
  created_at?: string | null;
}

/** Scrape job status returned by /api/scraping endpoints. */
export interface ScrapeJobResponse {
  id: number;
  name?: string | null;
  description?: string | null;
  source_url?: string | null;
  url?: string | null;
  scrape_config?: string | null;
  config: Record<string, unknown>;
  runtime: Record<string, unknown>;
  status: "pending" | "running" | "completed" | "failed" | "cancelled" | "cleaned_up";
  progress: number | null;
  progress_message?: string | null;
  images_scraped: number | null;
  album_id?: number | null;
  error_message?: string | null;
  error?: string | null;
  last_error_at?: string | null;
  created_at?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  output_directory?: string | null;
  output_dir?: string | null;
}

/** Paginated list of scraping jobs returned by GET /api/scraping/jobs. */
export interface ScrapingJobsResponse {
  jobs: Array<ScrapeJobResponse>;
  total: number;
  page: number;
  per_page: number;
  pages: number;
}

/** Aggregated scraping statistics returned by GET /api/scraping/stats. */
export interface ScrapingStatsResponse {
  total_jobs: number;
  total_images_scraped: number;
  recent_jobs: number;
  status_breakdown: Record<string, number>;
  storage: { path: string; total_gb?: number | null; used_gb?: number | null; free_gb?: number | null; free_percent?: number | null; error?: string | null } | null;
}

/** Albums eligible for training returned by GET /api/training/albums. */
export interface TrainingAlbumsResponse {
  albums: Array<AlbumResponse>;
}

/** Detailed log information returned by GET /api/training/{id}/logs. */
export interface TrainingLogResponse {
  training_run_id: number;
  status: "pending" | "queued" | "running" | "completed" | "failed" | "cancelled";
  progress: number;
  error_message?: string | null;
  log_path: string;
  log_available: boolean;
  logs: string;
}

/** Training run status returned by /api/training endpoints. */
export interface TrainingRunResponse {
  id: number;
  name: string;
  description?: string | null;
  training_config?: string | null;
  status: "pending" | "queued" | "running" | "completed" | "failed" | "cancelled";
  progress: number;
  final_checkpoint?: string | null;
  training_loss?: number | null;
  validation_loss?: number | null;
  error_message?: string | null;
  last_error_at?: string | null;
  created_at?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  dataset_path?: string | null;
  output_path?: string | null;
}

/** Envelope returned by GET /api/training. */
export interface TrainingRunsResponse {
  training_runs: Array<TrainingRunResponse>;
  pagination: { page: number; per_page: number; total: number; pages: number; has_next: boolean; has_prev: boolean };
}
