/* eslint-disable */
// AUTO-GENERATED BY scripts/generate_shared_types.py
// Do not edit this file manually.

/** Response payload returned by /api/auth/me. */
export interface AuthStatus {
  authenticated: boolean;
  email?: string | null;
  name?: string | null;
  picture?: string | null;
  role?: string | null;
  is_admin?: boolean | null;
  error?: string | null;
  message?: string | null;
}

/** Generation metadata saved alongside generated images. */
export interface ImageMetadata {
  prompt?: string;
  negative_prompt?: string;
  seed?: number;
  steps?: number;
  guidance_scale?: number;
  width?: number;
  height?: number;
  model?: string;
  lora_path?: string;
  lora_weight?: number;
  loras?: Array<{ path: string; weight: number }>;
  set_name?: string;
  card_data?: Record<string, unknown>;
}
