"""AUTO-GENERATED FILE. DO NOT EDIT.

Generated by scripts/generate_shared_types.py
"""

from __future__ import annotations

from typing import Any, Literal, NotRequired, Required, TypedDict


class AlbumDetailResponseTypedDict(TypedDict, total=False):
    """Album detail record returned by GET /api/albums/{id}."""

    id: Required[int]
    name: Required[str]
    description: NotRequired[str | None]
    album_type: Required[str]
    is_public: Required[bool]
    generation_prompt: NotRequired[str | None]
    generation_config: NotRequired[str | None]
    created_by: NotRequired[str | None]
    created_at: NotRequired[str | None]
    updated_at: NotRequired[str | None]
    image_count: Required[int]
    is_set_template: Required[bool]
    csv_data: NotRequired[str | None]
    base_prompt: NotRequired[str | None]
    prompt_template: NotRequired[str | None]
    style_suffix: NotRequired[str | None]
    example_theme: NotRequired[str | None]
    lora_config: NotRequired[str | None]
    template_item_count: Required[int]
    template_items_preview: Required[list[dict[str, Any]]]
    lora_count: Required[int]
    slug: Required[str]
    images: Required[list[ImageResponseTypedDict]]
    source_type: NotRequired[str | None]
    source_id: NotRequired[int | None]


class AlbumResponsePreviewImagesItem(TypedDict, total=False):
    id: Required[int]
    filename: Required[str]
    thumbnail_path: NotRequired[str | None]


class AlbumResponseTypedDict(TypedDict, total=False):
    """Album record returned by /api/albums endpoints."""

    id: Required[int]
    name: Required[str]
    description: NotRequired[str | None]
    album_type: Required[str]
    is_public: Required[bool]
    generation_prompt: NotRequired[str | None]
    generation_config: NotRequired[str | None]
    created_by: NotRequired[str | None]
    created_at: NotRequired[str | None]
    updated_at: NotRequired[str | None]
    image_count: Required[int]
    is_set_template: Required[bool]
    csv_data: NotRequired[str | None]
    base_prompt: NotRequired[str | None]
    prompt_template: NotRequired[str | None]
    style_suffix: NotRequired[str | None]
    example_theme: NotRequired[str | None]
    lora_config: NotRequired[str | None]
    template_item_count: Required[int]
    template_items_preview: Required[list[dict[str, Any]]]
    preview_images: NotRequired[list[AlbumResponsePreviewImagesItem]]
    lora_count: Required[int]
    slug: Required[str]
    images: NotRequired[list[dict[str, Any]]]
    source_type: NotRequired[str | None]
    source_id: NotRequired[int | None]


class AuthStatusTypedDict(TypedDict, total=False):
    """Response payload returned by /api/auth/me."""

    authenticated: Required[bool]
    email: NotRequired[str | None]
    name: NotRequired[str | None]
    picture: NotRequired[str | None]
    role: NotRequired[str | None]
    is_admin: NotRequired[bool | None]
    error: NotRequired[str | None]
    message: NotRequired[str | None]


class BatchGenerationResponseTypedDict(TypedDict, total=False):
    """Response returned after queuing batch generation jobs."""

    message: Required[str]
    album_id: Required[int]
    album_name: Required[str]
    batch_id: Required[str]
    job_ids: Required[list[int]]
    output_dir: Required[str]


class BatchSummaryTypedDict(TypedDict, total=False):
    """Summary record for generated image batches returned by /api/generation/batches."""

    batch_id: Required[str]
    album_id: Required[int]
    name: Required[str]
    album_type: NotRequired[str | None]
    image_count: Required[int]
    created: NotRequired[str | None]
    updated: NotRequired[str | None]
    preview_url: NotRequired[str | None]
    path: NotRequired[str | None]


class BatchesResponseTypedDict(TypedDict, total=False):
    """Envelope returned by GET /api/generation/batches."""

    batches: Required[list[BatchSummaryTypedDict]]


class BugReportSubmissionRequestEnvironment(TypedDict, total=False):
    mode: Required[str]
    appVersion: NotRequired[str | None]
    gitSha: NotRequired[str | None]
    buildTime: NotRequired[str | None]


class BugReportSubmissionRequestClientmeta(TypedDict, total=False):
    locationHref: Required[str]
    userAgent: NotRequired[str]
    platform: NotRequired[str]
    language: NotRequired[str]
    locale: NotRequired[str]
    timezone: NotRequired[str]
    viewport: NotRequired[BugReportSubmissionRequestClientmetaViewport]


class BugReportSubmissionRequestRecentlogsItem(TypedDict, total=False):
    level: Required[str]
    message: Required[str]
    args: Required[list[Any]]
    timestamp: Required[str]
    serializedArgs: Required[list[Any]]


class BugReportSubmissionRequestNetworkeventsItem(TypedDict, total=False):
    id: Required[str]
    method: Required[str]
    url: Required[str]
    started_at: Required[str]
    completed_at: NotRequired[str | None]
    duration_ms: NotRequired[int | None]
    status: NotRequired[int | None]
    ok: NotRequired[bool | None]
    trace_id: NotRequired[str | None]
    requestHeaders: Required[list[BugReportSubmissionRequestNetworkeventsItemRequestheadersItem]]
    responseHeaders: Required[list[BugReportSubmissionRequestNetworkeventsItemResponseheadersItem]]
    requestBody: NotRequired[str | None]
    responseBody: NotRequired[str | None]
    error: NotRequired[str]


class BugReportSubmissionRequestClientmetaViewport(TypedDict, total=False):
    width: Required[int]
    height: Required[int]


class BugReportSubmissionRequestNetworkeventsItemRequestheadersItem(TypedDict, total=False):
    name: Required[str]
    value: Required[str]


class BugReportSubmissionRequestNetworkeventsItemResponseheadersItem(TypedDict, total=False):
    name: Required[str]
    value: Required[str]


class BugReportSubmissionRequestTypedDict(TypedDict, total=False):
    """Payload accepted by POST /api/bug-reports."""

    description: Required[str]
    expectedBehavior: NotRequired[str | None]
    actualBehavior: NotRequired[str | None]
    stepsToReproduce: NotRequired[list[str]]
    environment: Required[BugReportSubmissionRequestEnvironment]
    clientMeta: Required[BugReportSubmissionRequestClientmeta]
    appState: Required[dict[str, Any]]
    recentLogs: Required[list[BugReportSubmissionRequestRecentlogsItem]]
    networkEvents: Required[list[BugReportSubmissionRequestNetworkeventsItem]]
    screenshot: NotRequired[str | None]
    screenshotError: NotRequired[str | None]


class BugReportSubmissionResponseTypedDict(TypedDict, total=False):
    """Response returned by POST /api/bug-reports."""

    success: Required[bool]
    report_id: Required[str]
    trace_id: Required[str]
    stored_at: NotRequired[str | None]


class ImageMetadataLorasItem(TypedDict, total=False):
    path: Required[str]
    weight: Required[float]


class ImageMetadataTypedDict(TypedDict, total=False):
    """Generation metadata saved alongside generated images."""

    prompt: NotRequired[str]
    negative_prompt: NotRequired[str]
    seed: NotRequired[float]
    steps: NotRequired[float]
    guidance_scale: NotRequired[float]
    width: NotRequired[float]
    height: NotRequired[float]
    model: NotRequired[str]
    lora_path: NotRequired[str]
    lora_weight: NotRequired[float]
    loras: NotRequired[list[ImageMetadataLorasItem]]


class ImageResponseTypedDict(TypedDict, total=False):
    """Complete image record returned by /api/images endpoints."""

    id: Required[int]
    filename: Required[str]
    storage_name: NotRequired[str | None]
    download_url: Required[str]
    thumbnail_url: Required[str]
    prompt: NotRequired[str | None]
    negative_prompt: NotRequired[str | None]
    seed: NotRequired[int | None]
    steps: NotRequired[int | None]
    guidance_scale: NotRequired[float | None]
    width: NotRequired[int | None]
    height: NotRequired[int | None]
    lora_config: NotRequired[str | None]
    is_nsfw: Required[bool]
    is_public: Required[bool]
    created_at: NotRequired[str | None]
    updated_at: NotRequired[str | None]
    file_path: NotRequired[str | None]
    thumbnail_path: NotRequired[str | None]
    labels: NotRequired[list[LabelTypedDict]]
    label_count: NotRequired[int | None]
    manual_label_count: NotRequired[int | None]


class JobTypedDict(TypedDict, total=False):
    """Job state returned by image generation endpoints."""

    id: Required[int]
    status: Required[Literal["queued", "running", "completed", "failed", "cancelled"]]
    prompt: Required[str]
    queue_position: NotRequired[int | None]
    submitted_at: Required[str]
    started_at: NotRequired[str | None]
    completed_at: NotRequired[str | None]
    cancelled_at: NotRequired[str | None]
    created_at: NotRequired[str]
    created: NotRequired[str]
    output_path: NotRequired[str | None]
    output_filename: NotRequired[str]
    output_directory: NotRequired[str]
    output_dir: NotRequired[str]
    output: NotRequired[str]
    lora_paths: NotRequired[list[str]]
    lora_weights: NotRequired[list[float]]
    width: NotRequired[int]
    height: NotRequired[int]
    steps: NotRequired[int]
    seed: NotRequired[int]
    guidance_scale: NotRequired[float]
    negative_prompt: NotRequired[str]
    error: NotRequired[str | None]
    duration_seconds: NotRequired[float]
    estimated_time_remaining: NotRequired[float | None]
    album_id: NotRequired[int]
    batch_id: NotRequired[str]
    batch_item_name: NotRequired[str]
    batch_item_data: NotRequired[dict[str, Any]]


class JobsResponseTypedDict(TypedDict, total=False):
    """Envelope returned by GET /api/jobs."""

    current: Required[JobTypedDict | None]
    queue: Required[list[JobTypedDict]]
    history: Required[list[JobTypedDict]]


class LabelTypedDict(TypedDict, total=False):
    """Label/tag associated with an image."""

    id: Required[int]
    image_id: Required[int]
    label_text: Required[str]
    confidence: NotRequired[float | None]
    label_type: Required[str]
    source_model: NotRequired[str | None]
    source_prompt: NotRequired[str | None]
    created_by: NotRequired[str | None]
    created_at: NotRequired[str | None]


class ScrapeJobResponseTypedDict(TypedDict, total=False):
    """Scrape job status returned by /api/scraping endpoints."""

    id: Required[int]
    name: NotRequired[str | None]
    description: NotRequired[str | None]
    source_url: NotRequired[str | None]
    url: NotRequired[str | None]
    scrape_config: NotRequired[str | None]
    config: Required[dict[str, Any]]
    runtime: Required[dict[str, Any]]
    status: Required[
        Literal["pending", "running", "completed", "failed", "cancelled", "cleaned_up"]
    ]
    progress: Required[int | None]
    progress_message: NotRequired[str | None]
    images_scraped: Required[int | None]
    album_id: NotRequired[int | None]
    error_message: NotRequired[str | None]
    error: NotRequired[str | None]
    last_error_at: NotRequired[str | None]
    created_at: NotRequired[str | None]
    started_at: NotRequired[str | None]
    completed_at: NotRequired[str | None]
    output_directory: NotRequired[str | None]
    output_dir: NotRequired[str | None]


class ScrapingJobsResponseTypedDict(TypedDict, total=False):
    """Paginated list of scraping jobs returned by GET /api/scraping/jobs."""

    jobs: Required[list[ScrapeJobResponseTypedDict]]
    total: Required[int]
    page: Required[int]
    per_page: Required[int]
    pages: Required[int]


class ScrapingStatsResponseStorage(TypedDict, total=False):
    path: Required[str]
    total_gb: NotRequired[float | None]
    used_gb: NotRequired[float | None]
    free_gb: NotRequired[float | None]
    free_percent: NotRequired[float | None]
    error: NotRequired[str | None]


class ScrapingStatsResponseTypedDict(TypedDict, total=False):
    """Aggregated scraping statistics returned by GET /api/scraping/stats."""

    total_jobs: Required[int]
    total_images_scraped: Required[int]
    recent_jobs: Required[int]
    status_breakdown: Required[dict[str, int]]
    storage: Required[ScrapingStatsResponseStorage | None]


class TrainingAlbumsResponseTypedDict(TypedDict, total=False):
    """Albums eligible for training returned by GET /api/training/albums."""

    albums: Required[list[AlbumResponseTypedDict]]


class TrainingLogResponseTypedDict(TypedDict, total=False):
    """Detailed log information returned by GET /api/training/{id}/logs."""

    training_run_id: Required[int]
    status: Required[Literal["pending", "queued", "running", "completed", "failed", "cancelled"]]
    progress: Required[float]
    error_message: NotRequired[str | None]
    log_path: Required[str]
    log_available: Required[bool]
    logs: Required[str]


class TrainingRunResponseTypedDict(TypedDict, total=False):
    """Training run status returned by /api/training endpoints."""

    id: Required[int]
    name: Required[str]
    description: NotRequired[str | None]
    training_config: NotRequired[str | None]
    status: Required[Literal["pending", "queued", "running", "completed", "failed", "cancelled"]]
    progress: Required[float]
    final_checkpoint: NotRequired[str | None]
    training_loss: NotRequired[float | None]
    validation_loss: NotRequired[float | None]
    error_message: NotRequired[str | None]
    last_error_at: NotRequired[str | None]
    created_at: NotRequired[str | None]
    started_at: NotRequired[str | None]
    completed_at: NotRequired[str | None]
    dataset_path: NotRequired[str | None]
    output_path: NotRequired[str | None]


class TrainingRunsResponsePagination(TypedDict, total=False):
    page: Required[int]
    per_page: Required[int]
    total: Required[int]
    pages: Required[int]
    has_next: Required[bool]
    has_prev: Required[bool]


class TrainingRunsResponseTypedDict(TypedDict, total=False):
    """Envelope returned by GET /api/training."""

    training_runs: Required[list[TrainingRunResponseTypedDict]]
    pagination: Required[TrainingRunsResponsePagination]
