"""AUTO-GENERATED FILE. DO NOT EDIT.

Generated by scripts/generate_shared_types.py
"""

from __future__ import annotations

from typing import NotRequired, Required, TypedDict


class AuthStatusTypedDict(TypedDict, total=False):
    """Response payload returned by /api/auth/me."""

    authenticated: Required[bool]
    email: NotRequired[str | None]
    name: NotRequired[str | None]
    picture: NotRequired[str | None]
    role: NotRequired[str | None]
    is_admin: NotRequired[bool | None]
    error: NotRequired[str | None]
    message: NotRequired[str | None]
