"""AUTO-GENERATED FILE. DO NOT EDIT.

Generated by scripts/generate_shared_types.py
"""

from __future__ import annotations

from typing import Any, NotRequired, Required, TypedDict


class AuthStatusTypedDict(TypedDict, total=False):
    """Response payload returned by /api/auth/me."""

    authenticated: Required[bool]
    email: NotRequired[str | None]
    name: NotRequired[str | None]
    picture: NotRequired[str | None]
    role: NotRequired[str | None]
    is_admin: NotRequired[bool | None]
    error: NotRequired[str | None]
    message: NotRequired[str | None]


class ImageMetadataLorasItem(TypedDict, total=False):
    path: Required[str]
    weight: Required[float]


class ImageMetadataTypedDict(TypedDict, total=False):
    """Generation metadata saved alongside generated images."""

    prompt: NotRequired[str]
    negative_prompt: NotRequired[str]
    seed: NotRequired[float]
    steps: NotRequired[float]
    guidance_scale: NotRequired[float]
    width: NotRequired[float]
    height: NotRequired[float]
    model: NotRequired[str]
    lora_path: NotRequired[str]
    lora_weight: NotRequired[float]
    loras: NotRequired[list[ImageMetadataLorasItem]]
    set_name: NotRequired[str]
    card_data: NotRequired[dict[str, Any]]
