tunnel: db1a99dd-3d12-4315-b241-da2a55a5c30f
credentials-file: /home/jdubz/.cloudflared/db1a99dd-3d12-4315-b241-da2a55a5c30f.json

ingress:
  # API endpoints go to Flask backend via dedicated subdomain
  - hostname: api.imagineer.joshwentworth.com
    service: http://localhost:10050

  # Fallback
  - service: http_status:404
