name: Frontend Tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'web/**'
      - '.github/workflows/test-frontend.yml'
  pull_request:
    paths:
      - 'web/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  test:
    name: Frontend Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18', '20', '21']

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        working-directory: ./web
        run: npm ci

      - name: Run linter
        working-directory: ./web
        run: npm run lint

      - name: Run tests
        working-directory: ./web
        run: npm test -- --run --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./web/coverage/lcov.info
          flags: frontend
          name: frontend-coverage-node-${{ matrix.node-version }}

      - name: Test build
        working-directory: ./web
        run: |
          npm run build
          test -f ../public/index.html
          test -d ../public/assets
          echo "✅ Build successful"

      - name: Test summary
        run: |
          echo "## Frontend Tests (Node ${{ matrix.node-version }}) ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Node Version:** ${{ matrix.node-version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Linting:** Passed" >> $GITHUB_STEP_SUMMARY
          echo "**Tests:** Passed" >> $GITHUB_STEP_SUMMARY
          echo "**Build:** Successful" >> $GITHUB_STEP_SUMMARY